services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: csb_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=webshop
      - RABBITMQ_DEFAULT_PASS=webshop123
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - csb_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  csb_sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: csb_sqlserver
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "CocoSunBags2025!"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - csb_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\" -b -o /dev/null || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s

  csb_webapi:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csb_api
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__CocoSunBagsWebshop: "Server=csb_sqlserver;Database=180005;User Id=sa;Password=CocoSunBags2025!;TrustServerCertificate=True;MultipleActiveResultSets=true;"
      RabbitMQ__HostName: rabbitMQ
      RabbitMQ__Port: "5672"
      RabbitMQ__UserName: webshop
      RabbitMQ__Password: webshop123
    networks:
      - csb_network
    depends_on:
      csb_sqlserver:
        condition: service_healthy
      rabbitMQ:
        condition: service_started

  csb_notifications:
    restart: unless-stopped
    build:
      context: .
      dockerfile: CSBWebshopSeminarski.Notifications/Dockerfile
    container_name: csb_notifications
    environment:
      RabbitMQ__HostName: rabbitMQ
      RabbitMQ__Port: "5672"
      RabbitMQ__UserName: webshop
      RabbitMQ__Password: webshop123
      RabbitMQ__Exchange: webshop.events
      RabbitMQ__OrderCreatedRoutingKey: orders.created
      Smtp__Host: smtp.gmail.com
      Smtp__Port: "587"
      Smtp__User: neirasetka@gmail.com
      Smtp__Pass: "abcd efgh ijkl mnop"
    depends_on:
      - csb_sqlserver
      - csb_webapi
      - rabbitMQ
    networks:
      - csb_network

volumes:
  sqlserverdata:
  rabbitmq_data:

networks:
  csb_network:
    driver: bridge
